### ISSUE TITLE
[Help] I'm unsure what to do 

### ISSUE THREAD

**Issue by Preflame24** [Ajarmar/universal-pokemon-randomizer-zx#408]
**Describe your problem clearly:** 

Im using a Macbook and downloaded the zip file, when I try to run the command to open the jar file it opens the terminal and runs a command, but it just asks for me to press return and nothing happens afterwards. Ive uninstalled and reinstalled java already, and I have tried to use the cd command in terminal as well. Can anyone help?

This is the command that runs in terminal when I click the command file

/Users/(MyName)/Desktop/PokeRandoZX-v4_3_0/launcher_MAC.command ; exit;
Name-Air:~ MyName$ /Users/(MyName)/Desktop/PokeRandoZX-v4_3_0/launcher_MAC.command ; exit;
Exception in thread "main" java.lang.UnsupportedClassVersionError: com/dabomstew/pkrandom/newgui/NewRandomizerGUI : Unsupported major.minor version 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClassCond(ClassLoader.java:637)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:621)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:141)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:283)
	at java.net.URLClassLoader.access$000(URLClassLoader.java:58)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:197)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
Press Enter to exit...
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

**System (please fill in the following information):**
 - Operating System: Macbook 
 - Randomizer Version: 4.3

**Comment by tom-overton** [comment]
Can you open a Terminal window and run `java -version`? This error indicates that you might have too old of a Java version installed.

**Comment by Preflame24** [comment]
This is what pops up 

Name-Air:~ (MyName)$ java -version
java version "1.6.0_65"
Java(TM) SE Runtime Environment (build 1.6.0_65-b14-468)
Java HotSpot(TM) 64-Bit Server VM (build 20.65-b04-468, mixed mode)

**Comment by tom-overton** [comment]
Yeah that indicates you have Java *6* installed, when you need Java *8* to use the randomizer. Head over to the [Java](https://github.com/Ajarmar/universal-pokemon-randomizer-zx/wiki/About-Java) section of our wiki and grab a 64-bit Java 8 (or higher) version for macOS. That should fix the problem you're seeing.

**Comment by Preflame24** [comment]
So ive uninstalled java and then reinstalled the java 8 version but it still doesnt work. after some testing its seems that terminal says im running version 6, but in my settings tab in the java plane it says im using version 8. It still doesnt run the command file either. 

This is the prompt that shows when I check the version in the terminal 

Last login: Sun Mar 27 21:04:03 on ttys000
Name-Air:~ (MyName)$ java -version
java version "1.6.0_65"
Java(TM) SE Runtime Environment (build 1.6.0_65-b14-468)
Java HotSpot(TM) 64-Bit Server VM (build 20.65-b04-468, mixed mode)
![Screen Shot 2022-03-27 at 9 08 05 PM](https://user-images.githubusercontent.com/102409940/160314560-01c94992-3317-419e-af2d-a8f050e93a74.png)

**Comment by tom-overton** [comment]
Do you have a `.bash_profile` in your home directory? If so, does it have a line that's something like `export JAVA_HOME="/System/Library/Frameworks/JavaVM.framework/Versions/1.6.0/Home"`? If so, you'll need to update JAVA_HOME to point towards your Java 8 installation

**Comment by Preflame24** [comment]
I'm unsure what you mean by this, I havent a clue what a home directory is. forgive me but I'm not the most techsavy when it comes to mac's

**Comment by tom-overton** [comment]
Sorry for the delay on responding; I've been very sick recently and haven't been able to reply until now.

Your "home directory" is simply the directory named after your username. If the Finder is open, you can click "Go" -> "Home" on the menu bar at the top of your screen to go to your home directory.
<img width="255" alt="Screen Shot 2022-03-30 at 9 28 59 PM" src="https://user-images.githubusercontent.com/12245827/160976890-45314a99-a584-4059-9258-15f53ff003ec.png">

Once you have Home opened in Finder, you can press Command + Shift + . to view "hidden files" in that directory (that last one is the "period" key). One of those hidden files might be named `.bash_profile`. If it is, double-click on it to open it and see if there's something in there about `JAVA_HOME`. You might also have a file called `.zshrc` or `.zshprofile`; if so, then check those places out too. If you *do* find something involving `JAVA_HOME`, then you'll need to change it to point it to your new Java 8 installation. When you're done, you can press Command + Shift + . to hide your hidden files again.

Unfortunately, you might be better off asking a Mac tech support forum of some sort than us; Ajarmar doesn't have a Mac, and my Mac is a work computer, so there isn't a lot I can actually do with it. Hope this helps, though!

**Comment by GB-CG** [comment]
Alternatively, you can use the Java Development Kit from https://jdk.java.net/18/
Open the `gz` file and move it to `*your mac volume name*/Library/Java/JavaVirtualMachines` (Not the `Library` folder in the `Home` folder), enter your password and then try double clicking the randomizer `jar` file.
